const jogos = [

  // ===== EM ALTA / POPULARES =====
  {
    id: "gd",
    nome: "Geometry Dash",
    developer: "RobTop Games",
    download: {
      steam: 'https://store.steampowered.com/app/322170/Geometry_Dash/',
      android: 'https://play.google.com/store/apps/details?id=com.robtopx.geometryjump',
      ios: 'https://apps.apple.com/app/geometry-dash/id625334537'
    },
    descricao: "Pule e voe pelo perigo neste jogo de plataforma de ação baseado em ritmo! Prepare-se para um desafio quase impossível no mundo do Geometry Dash.",
    thumb: "assets/thumbnail/Geometrydash.webp",
    type: "iframe",
    url: "https://geometrydash.com/game/index.html",
    rating: "L",
    esrb: "E",
    pegi: "3",
    cero: "A",
    grac: "ALL",
    snr: "9",
    tags: ["acao", "casual", "alta", "populares", "ritmo"]
  },
  {
    id: "stumble",
    nome: "Stumble Guys",
    developer: "Scopely",
    descricao: "Stumble Guys é um jogo de nocaute massivo para vários jogadores com até 32 jogadores online. Junte-se rodada após rodada de caos crescente para tropeçar em differentes níveis até que um vencedor seja coroado!",
    thumb: "assets/thumbnail/Stumbleguys.webp",
    type: "external",
    url: "https://www.stumbleguys.com/pt-BR/play",
    rating: "A10",
    esrb: "E",
    pegi: "3",
    cero: "A",
    grac: "ALL",
    snr: "9",
    tags: ["acao", "casual", "amigos", "alta", "populares"]
  },
  {
    id: "suika",
    nome: "Suika World",
    developer: "Suika World",
    thumb: "assets/thumbnail/suika.webp",
    type: "external",
    url: "https://suika.world/play/offline",
    rating: "AL",
    esrb: "RU",
    pegi: "RP",
    cero: "RP",
    grac: "RP",
    snr: "6",
    tags: ["casual", "puzzle", "alta"]
  },

  // ===== IO GAMES =====
  {
    id: "territorial",
    nome: "Territorial.io",
    developer: "David Tschacher",
    thumb: "assets/thumbnail/Territorial.webp",
    type: "iframe",
    url: "https://territorial.io/",
    rating: "L",
    esrb: "E",
    pegi: "3",
    cero: "A",
    grac: "ALL",
    snr: "9",
    tags: ["io", "amigos", "estrategia"]
  },
  {
    id: "deeeep",
    nome: "Deeeep.io",
    developer: "Federico Mouse",
    thumb: "assets/thumbnail/Deeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeep.webp",
    type: "iframe",
    url: "https://deeeep.io/",
    rating: "AL",
    esrb: "RU",
    pegi: "RP",
    cero: "RP",
    grac: "RP",
    snr: "9",
    tags: ["io", "casual", "amigos"]
  },
  {
    id: "slither",
    nome: "Slither.io",
    developer: "Lowly Labs",
    thumb: "assets/thumbnail/Slitherio.webp",
    type: "iframe",
    url: "http://slither.com/io/",
    rating: "L",
    esrb: "E",
    pegi: "3",
    cero: "A",
    grac: "ALL",
    snr: "6",
    tags: ["io", "casual", "amigos"]
  },
  {
    id: "agar",
    nome: "Agar.io",
    developer: "Miniclip",
    thumb: "assets/thumbnail/Agar.webp",
    type: "external",
    url: "https://agar.io/",
    rating: "A10",
    esrb: "E",
    pegi: "3",
    cero: "A",
    grac: "ALL",
    snr: "6",
    tags: ["io", "casual", "amigos"]
  },
  {
    id: "smashkarts",
    nome: "Smash Karts",
    developer: "Tall Team",
    thumb: "assets/thumbnail/smashkart.webp",
    type: "iframe",
    url: "https://smashkarts.io/",
    rating: "A10",
    esrb: "E10",
    pegi: "7",
    cero: "A",
    grac: "ALL",
    snr: "9",
    tags: ["io", "amigos", "acao", "corrida", "populares"]
  },
  {
    id: "zombsroyale",
    nome: "ZombsRoyale",
    developer: "End Game Interactive",
    thumb: "assets/thumbnail/zombsroyale.webp",
    type: "iframe",
    url: "https://zombsroyale.io/",
    rating: "A12",
    esrb: "RU",
    pegi: "RP",
    cero: "RP",
    grac: "RP",
    snr: "12",
    tags: ["io", "amigos", "acao"]
  },

  // ===== AÇÃO =====
  {
    id: "vampiresurvivor",
    nome: "Vampire Survivors",
    developer: "poncle",
    thumb: "assets/thumbnail/vampiresurvivor.webp",
    type: "external",
    url: "https://poncle.itch.io/vampire-survivors",
    rating: "10",
    esrb: "E10",
    pegi: "7",
    cero: "A",
    grac: "12",
    snr: "12",
    tags: ["acao"]
  },

  // ===== PUZZLE =====
  {
    id: "2048",
    nome: "2048",
    developer: "Gabriele Cirulli",
    download: "games/2048/index.html",
    thumb: "assets/thumbnail/2048.webp",
    type: "self",
    url: "games/2048/index.html",
    rating: "L",
    esrb: "E",
    pegi: "3",
    cero: "A",
    grac: "ALL",
    snr: "3",
    tags: ["puzzle", "casual"]
  },
  {
    id: "gridland",
    nome: "Gridland",
    developer: "Double Speak Games",
    thumb: "assets/thumbnail/gridland.webp",
    type: "iframe",
    url: "https://gridland.doublespeakgames.com/",
    rating: "L",
    esrb: "E",
    pegi: "3",
    cero: "A",
    grac: "ALL",
    snr: "6",
    tags: ["puzzle", "estrategia", "casual"]
  },
  {
    id: "penrose",
    nome: "Penrose",
    developer: "Double Speak Games",
    thumb: "assets/thumbnail/penrose.webp",
    type: "iframe",
    url: "https://penrose.doublespeakgames.com/",
    rating: "L",
    esrb: "E",
    pegi: "3",
    cero: "A",
    grac: "ALL",
    snr: "6",
    tags: ["puzzle", "criatividade"]
  },
  {
    id: "radum",
    nome: "Radüm",
    developer: "Double Speak Games",
    thumb: "assets/thumbnail/radum.webp",
    type: "iframe",
    url: "https://radum.doublespeakgames.com/",
    rating: "A10",
    esrb: "RU",
    pegi: "RP",
    cero: "RP",
    grac: "RP",
    snr: "9",
    tags: ["puzzle", "estrategia", "amigos"]
  },
  {
    id: "puddingmonster",
    nome: "Pudding Monsters",
    developer: "ZeptoLab",
    thumb: "assets/thumbnail/puddingmonster.webp",
    type: "external",
    url: "https://yell0wsuit.page/assets/games/pudding-monsters/index.html",
    rating: "L",
    esrb: "E",
    pegi: "3",
    cero: "A",
    grac: "ALL",
    snr: "6",
    tags: ["casual", "puzzle"]
  },

  // ===== CASUAL =====
  {
    id: "uselessweb",
    nome: "The Useless Web",
    developer: "Tim Holman",
    thumb: "assets/thumbnail/Uselessweb.webp",
    type: "iframe",
    url: "https://theuselessweb.com/",
    rating: "A10",
    esrb: "RU",
    pegi: "RP",
    cero: "RP",
    grac: "RP",
    snr: "6",
    tags: ["casual"]
  },
  {
    id: "cookieclicker",
    nome: "Cookie Clicker",
    developer: "Orteil",
    thumb: "assets/thumbnail/CookieClicker.webp",
    type: "external",
    url: "https://orteil.dashnet.org/cookieclicker/",
    rating: "L",
    esrb: "E",
    pegi: "3",
    cero: "A",
    grac: "ALL",
    snr: "6",
    tags: ["casual", "populares"]
  },
  {
    id: "flightoffancy",
    nome: "A Flight of Fancy",
    developer: "Double Speak Games",
    thumb: "assets/thumbnail/flightoffancy.webp",
    type: "iframe",
    url: "https://doublespeakgames.com/flight-of-fancy.html",
    rating: "L",
    esrb: "E",
    pegi: "3",
    cero: "A",
    grac: "ALL",
    snr: "6",
    tags: ["criatividade", "casual"]
  },
  {
    id: "minimetro",
    nome: "Mini Metro (beta)",
    developer: "Dino Polo Club",
    thumb: "assets/thumbnail/minimetro.webp",
    type: "iframe",
    url: "http://old.dinopoloclub.com/minimetro/",
    rating: "L",
    esrb: "E",
    pegi: "3",
    cero: "A",
    grac: "ALL",
    snr: "6",
    tags: ["criatividade", "casual"]
  },

  // ===== EDUCACIONAL =====
  {
    id: "portal",
    nome: "Portal do Aluno Darwin",
    developer: "Centro de Ensino Charles Darwin",
    thumb: "assets/thumbnail/darwin.webp",
    type: "external",
    url: "https://aluno.darwin.com.br/",
    rating: "",
    esrb: "",
    pegi: "",
    cero: "",
    grac: "",
    snr: "",
    tags: ["edu"]
  },
  {
    id: "neal",
    nome: "NEAL.FUN",
    developer: "Neal Agarwal",
    thumb: "assets/thumbnail/Neal.webp",
    type: "external",
    url: "https://neal.fun/",
    rating: "A12",
    esrb: "RU",
    pegi: "RP",
    cero: "RP",
    grac: "RP",
    snr: "12",
    tags: ["edu", "casual"]
  },
  {
    id: "wordle",
    nome: "Wordle",
    developer: "The New York Times",
    thumb: "assets/thumbnail/Wordle.webp",
    type: "external",
    url: "https://www.nytimes.com/games/wordle/index.html",
    rating: "L",
    esrb: "E",
    pegi: "3",
    cero: "A",
    grac: "ALL",
    snr: "3",
    tags: ["edu", "puzzle"]
  },
  {
    id: "termo",
    nome: "Termo",
    developer: "Fernando Serboncini",
    thumb: "assets/thumbnail/Termo.webp",
    type: "iframe",
    url: "https://term.ooo/",
    rating: "L",
    esrb: "E",
    pegi: "3",
    cero: "A",
    grac: "ALL",
    snr: "3",
    tags: ["edu", "puzzle"]
  },
  {
    id: "openguessr",
    nome: "OpenGuessr",
    developer: "OpenGuessr",
    thumb: "assets/thumbnail/openguessr.webp",
    type: "iframe",
    url: "https://openguessr.com/",
    rating: "A10",
    esrb: "RU",
    pegi: "RP",
    cero: "RP",
    grac: "RP",
    snr: "3",
    tags: ["edu", "casual"]
  },
  {
    id: "littlealchemy",
    nome: "Little Alchemy 2",
    developer: "Jakub Koziol",
    thumb: "assets/thumbnail/LittleAlchemist.webp",
    type: "iframe",
    url: "https://littlealchemy2.com/",
    rating: "L",
    esrb: "E",
    pegi: "3",
    cero: "A",
    grac: "ALL",
    snr: "3",
    tags: ["puzzle", "edu", "casual", "populares", "criatividade"]
  },

  // ===== ESTRATÉGIA =====
  {
    id: "bloons",
    nome: "Bloons TD 5",
    developer: "Ninja Kiwi",
    thumb: "assets/thumbnail/BloonsTD5.webp",
    type: "external",
    url: "https://www.newgrounds.com/portal/view/610995",
    rating: "L",
    esrb: "E",
    pegi: "3",
    cero: "A",
    grac: "ALL",
    snr: "9",
    tags: ["estrategia"]
  },

  // ===== CRIATIVIDADE / SOCIAL =====
  {
    id: "gartic",
    nome: "GarticPhone",
    developer: "Onrizon",
    thumb: "assets/thumbnail/GarticP.webp",
    type: "external",
    url: "https://garticphone.com/",
    rating: "A12",
    esrb: "RU",
    pegi: "RP",
    cero: "RP",
    grac: "RP",
    snr: "UserGen",
    tags: ["casual", "amigos", "criatividade"]
  },

  // ===== DOCE (Cut the Rope e similares) =====
  {
    id: "cuttherope",
    nome: "Cut the Rope",
    developer: "ZeptoLab",
    thumb: "assets/thumbnail/cuttherope.webp",
    type: "iframe",
    url: "https://ctrhome.github.io/games/cut-the-rope/play/famobi/",
    rating: "L",
    esrb: "E",
    pegi: "3",
    cero: "A",
    grac: "ALL",
    snr: "6",
    tags: ["casual", "puzzle", "doce"]
  },
  {
    id: "cuttheropeexp",
    nome: "Cut the Rope Experiments",
    developer: "ZeptoLab",
    thumb: "assets/thumbnail/cuttheropeexp.webp",
    type: "iframe",
    url: "https://ctrhome.github.io/play/cut-the-rope-experiments/",
    rating: "L",
    esrb: "E",
    pegi: "3",
    cero: "A",
    grac: "ALL",
    snr: "6",
    tags: ["casual", "puzzle", "doce"]
  },
  {
    id: "cuttheropeholiday",
    nome: "Cut the Rope Holiday Gift",
    developer: "ZeptoLab",
    thumb: "assets/thumbnail/cuttheropeholiday.webp",
    type: "iframe",
    url: "https://ctrhome.github.io/games/cut-the-rope-holiday-gift/play/",
    rating: "L",
    esrb: "E",
    pegi: "3",
    cero: "A",
    grac: "ALL",
    snr: "6",
    tags: ["casual", "puzzle", "doce"]
  },
  {
    id: "cuttheropett",
    nome: "Cut the Rope Time Travel",
    developer: "ZeptoLab",
    thumb: "assets/thumbnail/cuttheropett.webp",
    type: "iframe",
    url: "https://ctrhome.github.io/play/cut-the-rope-time-travel/",
    rating: "L",
    esrb: "E",
    pegi: "3",
    cero: "A",
    grac: "ALL",
    snr: "6",
    tags: ["casual", "puzzle", "doce"]
  },
  {
    id: "cuttherope2",
    nome: "Cut the Rope 2",
    developer: "ZeptoLab",
    thumb: "assets/thumbnail/cuttherope2.webp",
    type: "external",
    url: "https://yell0wsuit.page/assets/games/ctr2/index.html/",
    rating: "L",
    esrb: "E",
    pegi: "3",
    cero: "A",
    grac: "ALL",
    snr: "6",
    tags: ["casual", "puzzle", "doce"]
  },
  {
    id: "cuttheropemagic",
    nome: "Cut the Rope Magic",
    developer: "ZeptoLab",
    thumb: "assets/thumbnail/cuttheropemagic.webp",
    type: "iframe",
    url: "https://ctrhome.github.io/play/cut-the-rope-magic/",
    rating: "L",
    esrb: "E",
    pegi: "3",
    cero: "A",
    grac: "ALL",
    snr: "6",
    tags: ["casual", "puzzle", "doce"]
  },

  // ===== CLÁSSICOS FLASH (via Ruffle) =====
  // Para hospedar: baixe o .swf, coloque em games/flash/nomedojogo/jogo.swf
  // e crie um index.html com o Ruffle carregando o arquivo
  {
    id: "ageofwar",
    nome: "Age of War",
    developer: "Max Games",
    thumb: "assets/thumbnail/AgeofWar.webp",
    type: "external",
    url: "https://html5.gamedistribution.com/9467420d5c84482e9087276338a3a7b1/",
    rating: "12",
    esrb: "T",
    pegi: "12",
    cero: "B",
    grac: "12",
    snr: "9",
    tags: ["flash"]
  },
  {
    id: "burritobison",
    nome: "Burrito Bison: Launcha Libre",
    developer: "Juicy Beast",
    thumb: "assets/thumbnail/BurritoBison.webp",
    type: "iframe",
    url: "http://game168976.konggames.com/gamez/0016/8976/live/index.html",
    rating: "12",
    esrb: "E10",
    pegi: "7",
    cero: "A",
    grac: "12",
    snr: "9",
    tags: ["flash"]
  },
  // --- Papa's Series ---
  {
    id: "papas_freezeria",
    nome: "Papa's Freezeria",
    developer: "Flipline Studios",
    download: "games/flash/papas/papasfreezeria.swf",
    thumb: "assets/thumbnail/PapasFreezeria.webp",
    type: "self",
    url: "games/flash/papas/index.html",
    rating: "L",
    esrb: "E",
    pegi: "3",
    cero: "A",
    grac: "ALL",
    snr: "6",
    tags: ["flash", "casual", "doce"]
  },
  {
    id: "papas_burgeria",
    nome: "Papa's Burgeria",
    developer: "Flipline Studios",
    download: "games/flash/papas_burgeria/papasburgeria_v2.swf",
    thumb: "assets/thumbnail/PapasBurgueria.webp",
    type: "self",
    url: "games/flash/papas_burgeria/index.html",
    rating: "L",
    esrb: "E",
    pegi: "3",
    cero: "A",
    grac: "ALL",
    snr: "6",
    tags: ["flash", "casual"]
  },
  {
    id: "papas_pizzeria",
    nome: "Papa's Pizzeria",
    developer: "Flipline Studios",
    download: "games/flash/papas_pizzeria/papaspizzeria_v2.swf",
    thumb: "assets/thumbnail/PapasPizzeria.webp",
    type: "self",
    url: "games/flash/papas_pizzeria/index.html",
    rating: "L",
    esrb: "E",
    pegi: "3",
    cero: "A",
    grac: "ALL",
    snr: "6",
    tags: ["flash", "casual"]
  },
  {
    id: "papas_pancakeria",
    nome: "Papa's Pancakeria",
    developer: "Flipline Studios",
    download: "games/flash/papas_pancakeria/papaspancakeria_v2.swf",
    thumb: "assets/thumbnail/PapasPancakeria.webp",
    type: "self",
    url: "games/flash/papas_pancakeria/index.html",
    rating: "L",
    esrb: "E",
    pegi: "3",
    cero: "A",
    grac: "ALL",
    snr: "6",
    tags: ["flash", "casual"]
  },
  {
    id: "papas_hotdoggeria",
    nome: "Papa's Hot Doggeria",
    developer: "Flipline Studios",
    download: "games/flash/papas_hotdoggeria/papashotdoggeria_v2.swf",
    thumb: "assets/thumbnail/papaisveryhot.webp",
    type: "self",
    url: "games/flash/papas_hotdoggeria/index.html",
    rating: "L",
    esrb: "E",
    pegi: "3",
    cero: "A",
    grac: "ALL",
    snr: "6",
    tags: ["flash", "casual"]
  },
  {
    id: "papas_cheeseria",
    nome: "Papa's Cheeseria",
    developer: "Flipline Studios",
    download: "games/flash/papas_cheeseria/papascheeseria_102.swf",
    thumb: "assets/thumbnail/PapasCheeseria.webp",
    type: "self",
    url: "games/flash/papas_cheeseria/index.html",
    rating: "L",
    esrb: "E",
    pegi: "3",
    cero: "A",
    grac: "ALL",
    snr: "6",
    tags: ["flash", "casual"]
  },
  {
    id: "papas_donuteria",
    nome: "Papa's Donuteria",
    developer: "Flipline Studios",
    download: "games/flash/papas_donuteria/papasdonuteria_102.swf",
    thumb: "assets/thumbnail/PapasDonuteria.webp",
    type: "self",
    url: "games/flash/papas_donuteria/index.html",
    rating: "L",
    esrb: "E",
    pegi: "3",
    cero: "A",
    grac: "ALL",
    snr: "6",
    tags: ["flash", "casual", "doce"]
  },
  {
    id: "papas_wingeria",
    nome: "Papa's Wingeria",
    developer: "Flipline Studios",
    download: "games/flash/papas_wingeria/papaswingeria_v2.swf",
    thumb: "assets/thumbnail/PapasWingeria.webp",
    type: "self",
    url: "games/flash/papas_wingeria/index.html",
    rating: "L",
    esrb: "E",
    pegi: "3",
    cero: "A",
    grac: "ALL",
    snr: "6",
    tags: ["flash", "casual"]
  },
  {
    id: "papas_pastaria",
    nome: "Papa's Pastaria",
    developer: "Flipline Studios",
    download: "games/flash/papas_pastaria/papaspastaria_v2.swf",
    thumb: "assets/thumbnail/PapasPastaria.webp",
    type: "self",
    url: "games/flash/papas_pastaria/index.html",
    rating: "L",
    esrb: "E",
    pegi: "3",
    cero: "A",
    grac: "ALL",
    snr: "6",
    tags: ["flash", "casual"]
  },
  {
    id: "papas_sushiria",
    nome: "Papa's Sushiria",
    developer: "Flipline Studios",
    download: "games/flash/papas_sushiria/papassushiria_101.swf",
    thumb: "assets/thumbnail/PapasSushiria.webp",
    type: "self",
    url: "games/flash/papas_sushiria/index.html",
    rating: "L",
    esrb: "E",
    pegi: "3",
    cero: "A",
    grac: "ALL",
    snr: "6",
    tags: ["flash", "casual"]
  },
  {
    id: "papas_tacomia",
    nome: "Papa's Taco Mia",
    developer: "Flipline Studios",
    download: "games/flash/papas_tacomia/papastacomia_v2.swf",
    thumb: "assets/thumbnail/PapasTacoria.webp",
    type: "self",
    url: "games/flash/papas_tacomia/index.html",
    rating: "L",
    esrb: "E",
    pegi: "3",
    cero: "A",
    grac: "ALL",
    snr: "6",
    tags: ["flash", "casual"]
  },
  {
    id: "papas_scooperia",
    nome: "Papa's Scooperia",
    developer: "Flipline Studios",
    download: "games/flash/papas_scooperia/papasscooperia_v102.swf",
    thumb: "assets/thumbnail/PapasScooperia.webp",
    type: "self",
    url: "games/flash/papas_scooperia/index.html",
    rating: "L",
    esrb: "E",
    pegi: "3",
    cero: "A",
    grac: "ALL",
    snr: "6",
    tags: ["flash", "casual", "doce"]
  },
  {
    id: "papas_bakeria",
    nome: "Papa's Bakeria",
    developer: "Flipline Studios",
    download: "games/flash/papas_bakeria/papasbakeria.swf",
    thumb: "assets/thumbnail/PapasBakeria.webp",
    type: "self",
    url: "games/flash/papas_bakeria/index.html",
    rating: "L",
    esrb: "E",
    pegi: "3",
    cero: "A",
    grac: "ALL",
    snr: "6",
    tags: ["flash", "casual", "doce"]
  },

  // --- Ação / Aventura ---
  {
    id: "stickrpg",
    nome: "Stick RPG",
    developer: "XGen Studios",
    download: "games/flash/stickrpg/stickrpg.swf",
    thumb: "assets/thumbnail/StickRPG.webp",
    type: "self",
    url: "games/flash/stickrpg/index.html",
    rating: "A12",
    esrb: "RU",
    pegi: "RP",
    cero: "RP",
    grac: "RP",
    snr: "12",
    tags: ["flash", "casual", "puzzle"]
  },

  // --- Plataforma ---
  {
    id: "fancypants",
    nome: "Fancy Pants Adventure",
    developer: "Brad Borne",
    download: "games/flash/fancypants/FPAWorld1_07a.swf",
    thumb: "assets/thumbnail/sfp.webp",
    type: "self",
    url: "games/flash/fancypants/index.html",
    rating: "L",
    esrb: "E",
    pegi: "3",
    cero: "A",
    grac: "ALL",
    snr: "6",
    tags: ["flash", "casual", "acao"]
  },
  {
    id: "fancypants2",
    nome: "Fancy Pants Adventure: World 2 demo",
    developer: "Brad Borne",
    download: "games/flash/fancypants2/the-fancy-pants-adventure-world-2-demo.swf",
    thumb: "assets/thumbnail/sfp2.webp",
    type: "self",
    url: "games/flash/fancypants2/index.html",
    rating: "L",
    esrb: "E",
    pegi: "3",
    cero: "A",
    grac: "ALL",
    snr: "6",
    tags: ["flash", "casual", "acao"]
  },
  {
    id: "dinorun",
    nome: "Dino Run",
    developer: "Pixeljam",
    download: "games/flash/dinorun/dinorun.swf",
    thumb: "assets/thumbnail/DinoRun.webp",
    type: "self",
    url: "games/flash/dinorun/index.html",
    rating: "AL",
    esrb: "E",
    pegi: "3",
    cero: "A",
    grac: "ALL",
    snr: "6",
    tags: ["flash", "casual", "acao"]
  },
  {
    id: "learntofly",
    nome: "Learn to Fly",
    developer: "Light Bringer Games",
    download: "games/flash/learntofly/learn-to-fly-3789.swf",
    thumb: "assets/thumbnail/Learn2Fly.webp",
    type: "self",
    url: "games/flash/learntofly/index.html",
    rating: "AL",
    esrb: "E",
    pegi: "3",
    cero: "A",
    grac: "ALL",
    snr: "6",
    tags: ["flash", "casual"]
  },

  // --- Puzzle / Estratégia ---
  {
    id: "bloons1",
    nome: "Bloons (original)",
    developer: "Ninja Kiwi",
    download: "games/flash/bloons/bloons.swf",
    thumb: "assets/thumbnail/bloons.webp",
    type: "self",
    url: "games/flash/bloons/index.html",
    rating: "AL",
    esrb: "E",
    pegi: "3",
    cero: "A",
    grac: "ALL",
    snr: "9",
    tags: ["flash", "puzzle", "casual"]
  },
  {
    id: "bloons2",
    nome: "Bloons 2",
    developer: "Ninja Kiwi",
    download: "games/flash/bloons2/bloons2-2.swf",
    thumb: "assets/thumbnail/bloons2.webp",
    type: "self",
    url: "games/flash/bloons2/index.html",
    rating: "AL",
    esrb: "E",
    pegi: "3",
    cero: "A",
    grac: "ALL",
    snr: "9",
    tags: ["flash", "puzzle", "casual"]
  },
  {
    id: "bloonstd",
    nome: "Bloons Tower Defense",
    developer: "Ninja Kiwi",
    download: "games/flash/bloonstd/bloonstd_moved.swf",
    thumb: "assets/thumbnail/BloonsTD.webp",
    type: "self",
    url: "games/flash/bloonstd/index.html",
    rating: "AL",
    esrb: "E",
    pegi: "3",
    cero: "A",
    grac: "ALL",
    snr: "9",
    tags: ["flash", "estrategia", "puzzle"]
  },
  {
    id: "cursedtreasure",
    nome: "Cursed Treasure",
    developer: "IriySoft",
    download: "games/flash/cursedtreasure/cursedtreasure.swf",
    thumb: "assets/thumbnail/cursedgame.webp",
    type: "self",
    url: "games/flash/cursedtreasure/index.html",
    rating: "A10",
    esrb: "RU",
    pegi: "RP",
    cero: "RP",
    grac: "RP",
    snr: "9",
    tags: ["flash", "estrategia", "puzzle"]
  },
  {
    id: "gemcraft",
    nome: "Gemcraft",
    developer: "GameInABottle",
    download: "games/flash/gemcraft/gemcraft-1716.swf",
    thumb: "assets/thumbnail/GemCraft.webp",
    type: "self",
    url: "games/flash/gemcraft/index.html",
    rating: "A10",
    esrb: "RU",
    pegi: "RP",
    cero: "RP",
    grac: "RP",
    snr: "9",
    tags: ["flash", "estrategia", "puzzle"]
  },
  {
    id: "desconhecido2",
    nome: "Kingdom Rush",
    developer: "Ironhide Game Studio",
    download: "games/flash/desconhecido2/12180.swf",
    thumb: "assets/thumbnail/kingdomrush.webp",
    type: "self",
    url: "games/flash/desconhecido2/index.html",
    rating: "6",
    esrb: "E",
    pegi: "7",
    cero: "A",
    grac: "ALL",
    snr: "9",
    tags: ["flash", "estrategia", "puzzle"]
  },
  {
    id: "f&w@ForestTemple",
    nome: "Fireboy and Watergirl 1 Forest Temple",
    developer: "Oslo Albet",
    thumb: "assets/thumbnail/f&w@ForestTemple.webp",
    type: "iframe",
    url: "https://html5.gamedistribution.com/a55c9cc9c21e4fc683c8c6857f3d0c75/",
    rating: "L",
    esrb: "E",
    pegi: "3",
    cero: "A",
    grac: "ALL",
    snr: "6",
    tags: ["acao", "puzzle", "casual", "amigos"]
  },
  {
    id: "f&w2LightTemple",
    nome: "Fireboy and Watergirl 2 Light Temple",
    developer: "Oslo Albet",
    thumb: "assets/thumbnail/f&w2LightTemple.webp",
    type: "iframe",
    url: "https://html5.gamedistribution.com/383ad09b92c7446b9113cccc29630517/?",
    rating: "L",
    esrb: "E",
    pegi: "3",
    cero: "A",
    grac: "ALL",
    snr: "6",
    tags: ["acao", "puzzle", "casual", "amigos"]
  },
  {
    id: "f&w3IceTemple",
    nome: "Fireboy and Watergirl 3 Ice Temple",
    developer: "Oslo Albet",
    thumb: "assets/thumbnail/f&w3IceTemple.webp",
    type: "iframe",
    url: "https://html5.gamedistribution.com/f3a6e1ac0a77412289cbac47658b2b68/",
    rating: "L",
    esrb: "E",
    pegi: "3",
    cero: "A",
    grac: "ALL",
    snr: "6",
    tags: ["acao", "puzzle", "casual", "amigos"]
  },
  {
    id: "f&w4CrystalTemple",
    nome: "Fireboy and Watergirl 4 Crystal Temple",
    developer: "Oslo Albet",
    thumb: "assets/thumbnail/f&w4CrystalTemple.webp",
    type: "iframe",
    url: "https://html5.gamedistribution.com/3790681b69584409b7f681a8e400102d/",
    rating: "L",
    esrb: "E",
    pegi: "3",
    cero: "A",
    grac: "ALL",
    snr: "6",
    tags: ["acao", "puzzle", "casual", "amigos"]
  },
  {
    id: "f&w5Elements",
    nome: "Fireboy and Watergirl 5 Elements",
    developer: "Oslo Albet",
    thumb: "assets/thumbnail/f&w5Elements.webp",
    type: "iframe",
    url: "https://html5.gamedistribution.com/03f124074b0049f89fdace0cacf8ead5/",
    rating: "L",
    esrb: "E",
    pegi: "3",
    cero: "A",
    grac: "ALL",
    snr: "6",
    tags: ["acao", "puzzle", "casual", "amigos"]
  },
  {
    id: "f&w6FairyTales",
    nome: "Fireboy And Watergirl 6: Fairy Tales",
    developer: "Oslo Albet",
    thumb: "assets/thumbnail/f&w6FairyTales.webp",
    type: "iframe",
    url: "https://html5.gamedistribution.com/56da8a54fe204845b34ccff750d4a60b/",
    rating: "L",
    esrb: "E",
    pegi: "3",
    cero: "A",
    grac: "ALL",
    snr: "6",
    tags: ["acao", "puzzle", "casual", "amigos"]
  },
  {
    id: "f&w7Friends",
    nome: "Fireboy & Watergirl 7: and Friends",
    developer: "Oslo Albet",
    thumb: "assets/thumbnail/f&w7Friends.webp",
    type: "iframe",
    url: "https://html5.gamedistribution.com/d4a3629101574bc39bd8f9d1888ca58e/",
    rating: "L",
    esrb: "E",
    pegi: "3",
    cero: "A",
    grac: "ALL",
    snr: "6",
    tags: ["acao", "puzzle", "casual", "amigos"]
  },
  {
    id: "X3m",
    nome: "Moto X3M",
    developer: "Madpuffers",
    thumb: "assets/thumbnail/x3m.webp",
    type: "iframe",
    url: "http://www.friv.com/z/games/motox3m/index-x.html",
    rating: "A10",
    esrb: "RU",
    pegi: "RP",
    cero: "RP",
    grac: "RP",
    snr: "9",
    tags: ["acao", "casual", "flash"]
  },
  {
    id: "X3m2",
    nome: "Moto X3M 2",
    developer: "Madpuffers",
    thumb: "assets/thumbnail/x3m2.webp",
    type: "iframe",
    url: "https://storage.y8.com/y8-studio/html5/madpuffers/MotoX3M_2_new/?key=2365427&value=101993",
    rating: "A10",
    esrb: "RU",
    pegi: "RP",
    cero: "RP",
    grac: "RP",
    snr: "9",
    tags: ["acao", "casual", "flash"]
  },
  {
    id: "X3m3",
    nome: "Moto X3M 3",
    developer: "Madpuffers",
    thumb: "assets/thumbnail/x3m3.webp",
    type: "iframe",
    url: "http://storage.y8.com/y8-studio/html5/akeemywka/moto_x3m_3/index.html",
    rating: "A10",
    esrb: "RU",
    pegi: "RP",
    cero: "RP",
    grac: "RP",
    snr: "9",
    tags: ["acao", "casual", "flash"]
  },
  {
    id: "X3m4",
    nome: "Moto X3M Winter",
    developer: "Madpuffers",
    thumb: "assets/thumbnail/x3m4.webp",
    type: "iframe",
    url: "https://storage.y8.com/y8-studio/html5/madpuffers/MotoX3M_4_Winter_new/?key=2365427&value=148994/",
    rating: "A10",
    esrb: "RU",
    pegi: "RP",
    cero: "RP",
    grac: "RP",
    snr: "9",
    tags: ["acao", "casual", "flash"]
  },
  {
    id: "X3m5",
    nome: "Moto X3M Pool Party",
    developer: "Madpuffers",
    thumb: "assets/thumbnail/x3m5.webp",
    type: "iframe",
    url: "https://storage.y8.com/y8-studio/html5/madpuffers/MotoX3M_5_PoolParty_new/?key=2365427&value=164857",
    rating: "A10",
    esrb: "RU",
    pegi: "RP",
    cero: "RP",
    grac: "RP",
    snr: "9",
    tags: ["acao", "casual", "flash"]
  },
  {
    id: "X3m6",
    nome: "Moto X3M Spooky Land",
    developer: "Madpuffers",
    thumb: "assets/thumbnail/x3m6.webp",
    type: "iframe",
    url: "https://storage.y8.com/y8-studio/html5/madpuffers/MotoX3M_6_SpookyLand_new/?key=2365427&value=171349",
    rating: "A10",
    esrb: "RU",
    pegi: "RP",
    cero: "RP",
    grac: "RP",
    snr: "9",
    tags: ["acao", "casual", "flash"]
  },
];
